### ISSUE TITLE
Lesson 6: brownie run scripts/deploy.py --network rinkeby doesn't return anything or deploy 5:15:54

### ISSUE THREAD

**Issue by CrispyButter** [smartcontractkit/chainlink-brownie-contracts#16]
In lesson 6 I am at 5:15:54 where Patrick deploys the FundMe contract to Rinkeby. It compiled fine but when I tried to deploy to Rinkeby (below) it gives me no transaction details and I also do not see a deployment, only this:

```
Trell@Kentrells-MBP brownie_fund_me % brownie run scripts/deploy.py --network rinkeby
Brownie v1.16.4 - Python development framework for Ethereum

BrownieFundMeProject is the active project.

Running 'scripts/deploy.py::main'...
Trell@Kentrells-MBP brownie_fund_me % 
```
Please note that I do see a change in my scripts as this __pycache__ is created. not too sure what it does.:<img width="237" alt="image" src="https://user-images.githubusercontent.com/94574606/165370547-d598cb23-644f-4e02-9159-575ba6d2584a.png">

deploy.py 
```
from brownie import FundMe
from scripts.helpful_scripts import get_account


def deploy_fund_me():
    account = get_account()
    fund_me = FundMe.deploy({"from": account})
    print(f"Contract deployed to {fund_me.address}")


def main():
    deploy_fund_me
```
helpful_scripts.py
```
from brownie import network, config, accounts

def get_account():
    if network.show_active() == "development":
        return accounts[0]
    else:
        return accounts.add(config["wallets"]["from_key"])
```

brownie-config.yaml
```
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
dotenv: .env
wallets:
  "from_key": ${PRIVATE_KEY}
```

.env
```
export PRIVATE_KEY = 0xb9b6a469dbccf5a6defdaf03e40ec3c32aa2fffa8c25bd1bbeaf402fcdc86f57
export WEB3_INFURA_PROJECT_ID = 47dd43dcb45e43fdb30b0f168ef449c0
```
.env returned these problems but that was a non-issue when deploying SimpleStorage in previous lesson.

Finally here is a picture of my sidebar. I have been stuck for 2 days and 6+ hours and would love some assistance.<img width="231" alt="image" src="https://user-images.githubusercontent.com/94574606/165372322-65b1b6c3-5673-462e-bacf-b86bee90b219.png">
