### ISSUE TITLE
ParserError: Source "@chainlink/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol" not found: File not found. Searched the following locations: "".

### ISSUE THREAD

**Issue by ujwanviera** [smartcontractkit/chainlink-brownie-contracts#20]
I am taking @PatrickAlphaC tutorial but I am stack at one point. Brownie Fund Me course. I tried to compile it but it does not work.
here are my file (as the one provided by @PatrickAlphaC in the course repo).
Error:
![image](https://user-images.githubusercontent.com/85238382/194650437-fa0091e6-159f-4d7a-aa6a-0256b14696db.png)

brownie-config.yaml:
![image](https://user-images.githubusercontent.com/85238382/194649199-81d7ff43-7f8f-47f7-912e-971e30faadba.png)

FundMe.sol (a part of it as I copied it from the course repo and made no modifications):

![image](https://user-images.githubusercontent.com/85238382/194649662-0a75b807-9967-414c-83b7-bd9ea0f39d27.png)

Any idea of why I am having this error? I have been browsing on google trying to figure it out but with no success.
In my attempts I created a setting.json file as in some posts some one suggested that it works with it but for me the error kept coming up
setting.json:
![image](https://user-images.githubusercontent.com/85238382/194651006-d4c24f93-9852-4592-8e51-2db23c9c2d43.png)

Thank you.

**Comment by Tatendaz** [comment]
Hi @ujwanviera, 

I faced a similar issue and I ended up just using the same version as in the videos provided. For example in your contract use
<code>pragma solidity 0.6.6;</code>
And then import version 0.6 of the aggregatorV3Interface.sol

<code> import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";</code>

in you brownie-config/yaml file use 1.1.1
```
dependencies:
  # - <organization/repo>@version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1' 
```

If you still facing an issue let me know
