### ISSUE TITLE
Callback not supported

### ISSUE THREAD

**Issue by wombyz** [smartcontractkit/chainlink-brownie-contracts#8]
Getting error "Source "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol" not found: File import callback not supported" when working on the brownie fund me project.

Have played around with everything but even though they are downloaded and installed they are not used when compiling.

Reason I say that they are not being used is I get this error:

```
CompilerError:solc returned the following errors:

contracts/FundMe.sol:28:16: DeclarationError: Undeclared identifier.
        return priceFeed.version();
```

Meaning when creating the priceFeed object in the constructor it is not being created properly of type AggregatorV3Interface(____).

```
constructor(address _priceFeed) public {
        priceFeed = AggregatorV3Interface(_priceFeed);
        owner = msg.sender;
    }
```

Spent a few hours trying to solve this and still nothing so would be great to get a hand so I can proceed with the course!

**Comment by PatrickAlphaC** [comment]
What version of the chainlink contracts are you using?

**Comment by wombyz** [comment]
In FundMe.sol:
```
import "@chainlink/contracts/src/v0.6/interfaces/AggregatorV3Interface.sol";
import "@chainlink/contracts/src/v0.6/vendor/SafeMathChainlink.sol";
```

In yaml:
```
dependencies:
  # - <organization/repo>@<version>
  - smartcontractkit/chainlink-brownie-contracts@1.1.1
compiler:
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'
```
